### ISSUE TITLE
(Missing) systemtray with linklist

### ISSUE THREAD

**Issue by sailor79** [thkl/HM-Explorer#1]
A Systemtray with integrated Linklist (html open std. browser) to

- [x] HM-Webui
- [ ] CuxD
- [ ] devconfig
- [ ] Historian (IP set by user, if not present on CCU/RM), 
- [ ] expandable by user for special links (e.g. iobroker etc.)

**Comment by thkl** [comment]
a javascript error is fired when the main window was closed and the user choosed the webgui link from tray

**Comment by sailor79** [comment]
"Wrong" mouse over text on tray

>  (aber geiles Feature :-), Danke.. )

<img width="202" alt="bildschirmfoto 2017-07-04 um 08 23 43" src="https://user-images.githubusercontent.com/1407792/27817593-4706febe-6092-11e7-8849-d9799f92b3d1.png">

**Comment by thkl** [comment]
⊙.☉ seem there is a default text. Ok will change this.

**Comment by thkl** [comment]
fixed in 0.0.20
