### ISSUE TITLE
Implement App/ Systray icon

### ISSUE THREAD

**Issue by sailor79** [thkl/HM-Explorer#11]

**Comment by thkl** [comment]
Any graphical genius here ?

**Comment by sailor79** [comment]
Not really, but a first try:

![ic_launcher](https://user-images.githubusercontent.com/1407792/27789520-470853e0-5fed-11e7-87af-7e0a910fb72c.png)

**Comment by sailor79** [comment]
oder 
![unknown3](https://user-images.githubusercontent.com/1407792/27789958-c4f2f9b2-5fee-11e7-8540-bed28deae723.png)

**Comment by thkl** [comment]
Letzteres ist hübsch :)

**Comment by sailor79** [comment]
[hm-ex_iconset.zip](https://github.com/thkl/HM-Explorer/files/1119268/hm-ex_iconset.zip)

**Comment by thkl** [comment]
see #1

**Comment by sailor79** [comment]
On Mac (probably Win, too):
Background of images is now transparent and therefore not visible enough:
<img width="283" alt="bildschirmfoto 2017-07-04 um 08 12 46" src="https://user-images.githubusercontent.com/1407792/27817371-02d5ac50-6091-11e7-8839-a7601ff38e12.png">
<img width="47" alt="bildschirmfoto 2017-07-04 um 08 13 18" src="https://user-images.githubusercontent.com/1407792/27817374-0540e112-6091-11e7-94e3-766d7902181c.png">

**Comment by thkl** [comment]
Oops 🙊 I will change this.

**Comment by sailor79** [comment]
Note: Through integrated update-procedure to 0.0.19 new icons are not visible (only old icon), only by re-installation it worked

**Comment by thkl** [comment]
shoulb be ok in 0.0.21
