### ISSUE TITLE
Typography and german umlauts

### ISSUE THREAD

**Issue by sailor79** [thkl/HM-Explorer#4]
> - Es fehlen einige Bindestriche, z.B. "Objekte des Variablen Objekts" -> "Objekte des Variablen-Objekts" (-> analog auch "Device-Objekt" etc.)
> - Tippfehler bei Funktionsbeschreibung "Ermittelt ob das Objet dem Typ..." 
> - "Gerät Aktiv ?" -> "Geraet Aktiv?"
> - "Antwort der CCU :" -> "Antwort der CCU:"
> - "Ermittelt den Namen des Objectes" ->"Ermittelt den Namen des Objektes"
> - "Liefert die ID des Geraet des Kanals" -> "Liefert die ID des Geraets des Kanals"
> - schön wäre wenn in den Texten Umlaute statt ae etc. verwendet würden.
> - Spaltenüberschriften der "Details-Tabelle" sind als einzige englisch -> property/value -> Eigenschaft/Wert
> - vorheriger Punkt nicht ganz Korrekt :) In der Variablen-Tabelle: Unit -> Einheit
> - "Logicwert" -> "Logikwert" 
> - in den Tabellen unten stehen die Überschriften etwas zu weit hinten. (-> nicht bündig mit den Werten in den Spalten wie bei den oberen Tabellen)

[https://homematic-forum.de/forum/viewtopic.php?f=66&t=37718&start=60#p370220](url)
[https://homematic-forum.de/forum/viewtopic.php?f=66&t=37718&start=70#p370257](url)

**Comment by thkl** [comment]
Should work in 0.0.17

**Comment by sailor79** [comment]
Found in 0.0.18:

![superscreenshot 2017-7-3 11-38-57](https://user-images.githubusercontent.com/1407792/27787272-843ce176-5fe4-11e7-9447-1202dbbe2693.png)
