### ISSUE TITLE
Device icons without background

### ISSUE THREAD

**Issue by sailor79** [thkl/HM-Explorer#5]
[https://homematic-forum.de/forum/viewtopic.php?f=66&t=37718&start=60#p370220](url)
> - Einige Geräteicons haben keinen Hintergrund (-> z.B. "neues" Wandthermostat und Zwischenstecker, Fensterkontakt)

[https://homematic-forum.de/forum/viewtopic.php?f=66&t=37718&start=70#p370257](url)

> Edit: Zu den Bildern der Geräte, diese lade ich beim Anzeigen direkt aus der CCU, die liegen also schon so kaputt (ohne Transparenz) in der CCU.

**Comment by thkl** [comment]
As described in the corresponding forum thread, the app is loading the images from your ccu.

**Comment by sailor79** [comment]
just for documentation...
