### ISSUE TITLE
Große Scripte ohne Ausgabe

### ISSUE THREAD

**Issue by robdg80** [thkl/HM-Explorer#8]
Wenn ich ein größeres Script ausführen lasse, kommt keine Ausgabe (Das Script läuft auf der CCU auch einige Sekunden, kommt dort aber zum Ende).

[SYS_WM_GarageRefresh2.txt](https://github.com/thkl/HM-Explorer/files/1118879/SYS_WM_GarageRefresh2.txt)
[SYS_CCU_Servicemeldungen_1.8.txt](https://github.com/thkl/HM-Explorer/files/1118882/SYS_CCU_Servicemeldungen_1.8.txt)

**Comment by thkl** [comment]
Note to myself increase TimeOut
